monolog:
  channels: [
    'tiger_connect.general'
  ]

  handlers:
    file_log:
      type: rotating_file
      path: "%kernel.logs_dir%/tigeruniconta-%kernel.environment%.log"
      level: info
      max_files: 15
      channels: [
        tiger_connect.general
      ]